services:
  - type: web
    name: fb-insta-downloader
    env: node
    buildCommand: |
      chmod +x ./render-setup.sh
      ./render-setup.sh
      npm install
    startCommand: npm start
    envVars:
      - key: RENDER
        value: true
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
