services:
  - type: web
    name: fb-insta-downloader
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      chmod +x ./render-setup.sh
      ./render-setup.sh
      npm install --production
      # Mise à jour du PATH pour yt-dlp
      export PATH=$HOME/.local/bin:$PATH
    startCommand: npm start
    envVars:
      - key: YT_DLP_PATH
        value: $HOME/.local/bin/yt-dlp  # Chemin corrigé
      - key: NODE_ENV
        value: production
      - key: PATH
        value: $HOME/.local/bin:$PATH  # Ajout au PATH système
    healthCheckPath: /health
    autoDeploy: true
