services:
  - type: web
    name: fb-insta-downloader
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y python3-pip ffmpeg
      pip3 install yt-dlp
      npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
