services:
  - type: web
    name: fb-insta-downloader
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      chmod +x ./render-setup.sh
      ./render-setup.sh
      npm install --production
    startCommand: npm start
    envVars:
      - key: YT_DLP_PATH
        value: /usr/local/bin/yt-dlp
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: tru
