services:
  - type: web
    name: fb-insta-downloader
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      # Installation sans Python
      mkdir -p $HOME/.local/bin
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o $HOME/.local/bin/yt-dlp
      chmod +x $HOME/.local/bin/yt-dlp
      npm install --production
    startCommand: npm start
    envVars:
      - key: YT_DLP_PATH
        value: $HOME/.local/bin/yt-dlp  # Chemin correct
      - key: NODE_ENV
        value: production
      - key: PATH
        value: $HOME/.local/bin:$PATH  # Inclut le chemin yt-dlp
    healthCheckPath: /health
    autoDeploy: true
